apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentinel-frontend-ingress
  namespace: sentinel-monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - portal.azmin.net
    secretName: sentinel-portal-tls
  rules:
  - host: portal.azmin.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sentinel-frontend-service
            port:
              number: 80
