- hosts: localhost
  become: yes
  tasks:
    - name: Install basic tools
      apt:
        name: [curl, git, python3-pip]
        state: present

    - name: Download K3s (The Manager)
      shell: curl -sfL https://get.k3s.io | sh -s - --disable traefik
